version: "3"

services:
  nginx:
    image: docker.io/nginx:alpine
    restart: unless-stopped
    ports:
      - ${WORDPRESS_PORT}:8000
      - ${PHPMYADMIN_PORT}:8001
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wordpress:/var/www/html:ro
      - phpmyadmin:/var/www/phpmyadmin:ro

  wordpress:
    image: docker.io/wordpress:fpm-alpine
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./wordpress:/var/www/html

  ftp:
    image: docker.io/delfer/alpine-ftp-server
    restart: unless-stopped
    depends_on:
      - wordpress
    environment:
      USERS: "${FTP_USER}|${FTP_PASSWORD}|/var/www/html/wp-content"
      ADDRESS: ftp
    volumes:
      - ./wordpress:/var/www/html

  mariadb:
    image: ghcr.io/linuxserver/mariadb:alpine
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mariadb:/config/databases

  phpmyadmin:
    image: docker.io/phpmyadmin:fpm-alpine
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - phpmyadmin:/var/www/html
    environment:
      PMA_HOST: mariadb

volumes:
    phpmyadmin:
